### ISSUE TITLE
Update `git clone` command in README to include submodules

### ISSUE THREAD

**Issue by fredcallaway** [jtth/jspsi-go-example#1]
Using the command `git clone https://github.com/jtth/jspsi-go-example.git` doesn't clone the submodule, so the jsPsych library isn't actually downloaded and nothing works. Replace this with

```
git clone --recursive https://github.com/jtth/jspsi-go-example.git
```

You can mention that users can leave out the `--recursive` if they'd rather symlink their local copy in.

http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by saralilyb** [comment]
Thanks! I updated the README to reflect this. I've never been good with submodules.
